version: '3.4'

services:

  application.api:
    container_name: application.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
        - application.db
    ports:
        - "8006:80"

  application.db:
    container_name: application.db
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"